# Generated by Django 2.1.7 on 2019-05-16 05:27

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=80)),
                ('book_id', models.CharField(max_length=80)),
                ('book_name', models.CharField(max_length=80)),
                ('index', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('deleverd', models.BooleanField(default=True)),
                ('img', models.CharField(max_length=100)),
                ('prd_name', models.CharField(max_length=100)),
                ('total', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('order_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=80)),
                ('book_id', models.CharField(max_length=80, unique=True)),
                ('price', models.FloatField()),
                ('address', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('pin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='ProductChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('product_id', models.IntegerField(unique=True)),
                ('discription', models.CharField(max_length=200)),
                ('choice', models.CharField(choices=[('Chocolate', 'Chocolate'), ('Biscuit', 'Biscuit'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Flower', 'Flower'), ('Mobile', 'Mobile')], max_length=20, verbose_name='choice')),
                ('img', models.ImageField(upload_to='proimg')),
            ],
        ),
        migrations.CreateModel(
            name='SingUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=40, verbose_name='Full Name')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('is_block', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
