# Generated by Django 2.1.7 on 2019-05-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile'),
        ),
    ]
