# Generated by Django 2.1.7 on 2019-05-18 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190518_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_block',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_otp_verified',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='otp',
        ),
    ]
